// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpkzcjnstgiaorkzzcqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwa3pjam5zdGdpYW9ya3p6Y3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NzA2MzIsImV4cCI6MjA1ODU0NjYzMn0.cNc2zQdUyn4_JH04GQewyrZeuNvAoFelk6g2twwJLo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);